/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#fcf8fa',
        surface: '#fcf8fa',
        'surface-dim': '#dcd9db',
        'surface-bright': '#fcf8fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f5',
        'surface-container': '#f0edef',
        'surface-container-high': '#eae7e9',
        'surface-container-highest': '#e4e2e4',
        'surface-variant': '#e4e2e4',
        'surface-tint': '#565e74',
        'on-surface': '#1b1b1d',
        'on-surface-variant': '#45464d',
        'on-background': '#1b1b1d',
        'inverse-surface': '#303032',
        'inverse-on-surface': '#f3f0f2',
        // primary was '#000000' (pure black) — too flat against the off-white
        // surfaces. Aligned with the existing primary-container deep navy so
        // primary text gets brand identity instead of generic body color.
        primary: '#1b2240',
        'on-primary': '#ffffff',
        'primary-container': '#131b2e',
        'on-primary-container': '#7c839b',
        'primary-fixed': '#dae2fd',
        'primary-fixed-dim': '#bec6e0',
        'on-primary-fixed': '#131b2e',
        'on-primary-fixed-variant': '#3f465c',
        'inverse-primary': '#bec6e0',
        secondary: '#0051d5',
        'on-secondary': '#ffffff',
        'secondary-container': '#316bf3',
        'on-secondary-container': '#fefcff',
        'secondary-fixed': '#dbe1ff',
        'secondary-fixed-dim': '#b4c5ff',
        'on-secondary-fixed': '#00174b',
        'on-secondary-fixed-variant': '#003ea8',
        // tertiary was also '#000000'. Mapped to the deep amber that
        // tertiary-container/tertiary-fixed-dim already imply so accents
        // (badges, highlights) actually look tertiary instead of black.
        tertiary: '#574425',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#271901',
        'on-tertiary-container': '#98805d',
        'tertiary-fixed': '#fcdeb5',
        'tertiary-fixed-dim': '#dec29a',
        'on-tertiary-fixed': '#271901',
        'on-tertiary-fixed-variant': '#574425',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        outline: '#76777d',
        'outline-variant': '#c6c6cd',
        'professional-blue': '#2563eb',
        'match-green': '#22c55e',
        'info-blue': '#3b82f6',
        success: '#22c55e',
        'success-container': '#bbf7d0',
      },
      keyframes: {
        shimmer: {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'fade-in': {
          '0%':   { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-up': {
          '0%':   { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          '0%':   { opacity: '0', transform: 'scale(0.96)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'slide-in-right': {
          '0%':   { opacity: '0', transform: 'translateX(16px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%':      { opacity: '0.55' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%':      { transform: 'translateY(-6px)' },
        },
      },
      animation: {
        shimmer:          'shimmer 1.4s ease-in-out infinite',
        'fade-in':        'fade-in 200ms ease-out both',
        'fade-up':        'fade-up 320ms cubic-bezier(0.16, 1, 0.3, 1) both',
        'scale-in':       'scale-in 200ms cubic-bezier(0.16, 1, 0.3, 1) both',
        'slide-in-right': 'slide-in-right 240ms cubic-bezier(0.16, 1, 0.3, 1) both',
        'pulse-soft':     'pulse-soft 2s ease-in-out infinite',
        float:            'float 4s ease-in-out infinite',
      },
      spacing: {
        unit: '4px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'stack-xl': '48px',
        'stack-gap': '16px',
        gutter: '24px',
        'card-padding': '24px',
        'margin-desktop': '48px',
        'sidebar-width': '260px',
        'container-max-width': '1280px',
      },
      maxWidth: {
        container: '1280px',
        'container-max-width': '1280px',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        ambient: '0px 4px 20px rgba(15, 23, 42, 0.05)',
        hover: '0px 10px 30px rgba(15, 23, 42, 0.10)',
        overlay: '0px 24px 80px rgba(15, 23, 42, 0.28)',
        'ambient-lvl1': '0px 4px 20px rgba(15, 23, 42, 0.05)',
        'ambient-lvl2': '0px 10px 30px rgba(15, 23, 42, 0.10)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Inter', 'system-ui', 'sans-serif'],
        h1: ['Inter', 'system-ui', 'sans-serif'],
        h2: ['Inter', 'system-ui', 'sans-serif'],
        h3: ['Inter', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'body-sm': ['Inter', 'system-ui', 'sans-serif'],
        'label-md': ['Inter', 'system-ui', 'sans-serif'],
        'label-sm': ['Inter', 'system-ui', 'sans-serif'],
        'ai-score': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        h1: ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['18px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'ai-score': ['20px', { lineHeight: '1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
